feat: orchestrion job server to reduce duplicated effort
DataDog/orchestrion pull request #176
Opened 2024-07-22 12:56 UTC by RomainMuller

A new integrated job-server using the NATS protocol is used to share effort between all involved processes. This reduces the amount of duplicated work that may be going on; while remaining auditable.

The job-server is a simple request-response server. A server is started automatically when relevant, listening to a randomly chosen available port on the loopback interface (via address `127.0.0.1`):

- When using `orchestrion go [build|list|...]`, the job-server is started by the root `orchestrion` process and shared to all children via a dedicated environment variable;
- When using `-toolexec="orchestrion toolexec"` (either directly or via `GOFLAGS`), a new job-server is started by the first `toolexec` invocation that needs one; and the connect URL is stored in a specific file within the `go` toolchain's `$WORK` directory, so that other `toolexec` processes can discover and use it. Such servers automatically shut down once the `$WORK` directory is destroyed, or if they have not had any client connected for a set time (`15` minutes).

Job servers maintain a cache of responses provided to requests, and only compute a given result once. As of this PR, the job server handles:

- Computing the version information added to `-V=full` command invocations, although this can only benefit from a shared job server if the build is started by `orchestrion go`, as otherwise these commands are invoked _before_ the `$WORK` directory is created;
- Resolving injected packages' export files, which is a common source of duplicated effort, as the `go toolchain` did not know about these and hence did not account for these dependencies when building the job tree, such that multiple concurrent resolutions may be attempted.

2024-08-06 15:40 UTC, eliottness requested changes
Overall looks very good already but very tiring to review

2024-08-06 15:40 UTC, eliottness commented on internal/jobserver/server.go
> +		}
Are we sure this won't cause client-side issue if the handlers are not even subscribed?

2024-08-06 15:40 UTC, eliottness commented on internal/cmd/server.go
> +	Action: func(c *cli.Context) error {
There is about 70% of this function being behind `urlFile != ""` two if statements. How about reversing the logic here or at least moving it in another function dedicated to the non-happy path ?

2024-08-06 15:40 UTC, eliottness commented on internal/cmd/server.go
> +		if urlFile != "" {
Above suggestion extents to this if statement :point_up:

2024-08-06 15:40 UTC, eliottness commented on internal/cmd/server.go
> +				log.Warnf("Failed to create file watcher: %v\n", err)
This `if` is very inconspicuous but brings great issues. How about explaining the issue clearly in 2/3 lines for the user?

2024-08-06 15:40 UTC, eliottness commented on internal/jobserver/server.go
> +		return
Maybe logging something here is not too bad

2024-08-06 15:40 UTC, eliottness commented on internal/jobserver/client/env.go
> +	if client == nil {
Can you revert this if statement and make it a returning-if to lower tabulation levers?

2024-08-06 15:40 UTC, eliottness commented on internal/jobserver/client/env.go
> +		} else if workDir != "" {
Same here with the code line 94-95

2024-08-06 15:40 UTC, eliottness commented on internal/jobserver/client/env.go
> +		} else if workDir != "" {
Or make all of this a switch case as you wish

2024-08-06 15:40 UTC, eliottness commented on internal/jobserver/client/env.go
> +			}
You should be able to put this in a separate function without too much issues

2024-08-07 07:51 UTC, RomainMuller commented on internal/jobserver/client/client.go
> +	HDR_CLIENT_PPID = "client-ppid" // Header containing the client parent PID
Goland is right! This is left over from an experiment I ended up not liking AT ALL.

2024-08-07 07:54 UTC, RomainMuller commented on internal/jobserver/run.go
Ooops, forgot to delete!

2024-08-07 07:55 UTC, RomainMuller commented on internal/log/level.go
> +
Ah this is also dead code from back when I made this experiment I didn't like at all ^^

2024-08-07 11:34 UTC, eliottness approved these changes
LGTM

2024-08-07 12:04 UTC, merged