fix: net/http server-side instrumentation
DataDog/orchestrion pull request #403
Opened 2024-11-19 12:07 UTC by rarguelloF

2024-11-20 14:25 UTC, nsrip-dd approved these changes
Thanks! The general approach makes sense to me. I haven't reviewed this PR deeply. I'll leave that to the Orchestrion experts. I tried this PR out locally on a Go HTTP server we use in the profiling backend that uses ServeMux (the one that motivated #173). I confirmed that the handler gets instrumented :)

2024-11-20 17:29 UTC, RomainMuller requested changes

2024-11-20 17:29 UTC, RomainMuller commented on internal/toolexec/aspect/oncompile.go
> +func (w Weaver) OnCompile(cmd *proxy.CompileCommand) (result error) {
⚠️ I'm going to do a refactor of this monstrosity tomorrow before we can merge this.

2024-11-21 10:11 UTC, RomainMuller approved these changes

2024-11-22 11:57 UTC, merged